home/urls.py
from django.urls import path, include
from home.views import home_page, about_page

urlpatterns = [
    path("home/", home_page, name="home_page"),
    path("about/", about_page, name="about_page"),
]

tasks/urls.py
from django.urls import path
from tasks.views import (
    create_task,
    list_task,
    update_task,
    task_detail,
)

app_name = "mytasks"

urlpatterns = [
    path("create/", create_task, name="create_task"),
    path("mine/", list_task, name="show_my_tasks"),
    path("mine/<int:id>/edit/", update_task, name="edit_tasks"),
    path("mine/<int:id>/detail/", task_detail, name="task_detail"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect


def redirect_to_home(request):
    return redirect("home_page")


def redirect_to_login(request):
    return redirect("login")


def redirect_to_project(request):
    return redirect("list_projects")


urlpatterns = [
    path("", redirect_to_home, name="home"),
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path("accounts/", include("accounts.urls")),
    path("accounts/", redirect_to_login, name="account_page"),
    path("projects/", redirect_to_project, name="project_page"),
    path("tasks/", include("tasks.urls", namespace="mytasks")),
    path("", include("home.urls")),
]

tasks/models.py
from django.db import models
from projects.models import Project, USER_MODEL, ProjectCategory


# Create your models here.
class TaskTag(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Task(models.Model):
    class TaskStatus(models.TextChoices):
        Not_started = "Not Started"
        In_progress = "In Progress"
        Blocked = "Blocked"
        Complete = "Complete"

    class TaskPriority(models.TextChoices):
        Urgent = "Urgent"
        High = "High"
        Moderate = "Moderate"
        Low = "Low"
        Blank = "-"

    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        Project,
        related_name="tasks",
        on_delete=models.CASCADE,
    )
    assignee = models.ForeignKey(
        USER_MODEL,
        related_name="tasks",
        null=True,
        on_delete=models.CASCADE,
    )
    description = models.TextField(null=True)
    status = models.CharField(
        max_length=200,
        null=True,
        choices=TaskStatus.choices,
        default=TaskStatus.Not_started,
    )
    priority = models.CharField(
        max_length=200,
        null=True,
        choices=TaskPriority.choices,
        default=TaskPriority.Blank,
    )
    category = models.ForeignKey(
        ProjectCategory,
        related_name="tasks",
        null=True,
        on_delete=models.SET_NULL,
    )
    tag = models.ManyToManyField(
        TaskTag,
        related_name="tasks",
        blank=True,
    )

    def __str__(self):
        return f"{self.name}"

tasks/forms.py
from django.forms import ModelForm
from tasks.models import Task
from django.forms.widgets import DateInput
from django import forms


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = [
            "name",
            "start_date",
            "due_date",
            "project",
            "assignee",
            "description",
            "status",
            "priority",
            "category",
        ]
        widgets = {
            "start_date": DateInput(attrs={"type": "date"}),
            "due_date": DateInput(attrs={"type": "date"}),
            "is_completed": forms.CheckboxInput(
                attrs={"class": "form-check-input"}
            ),
        }

tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from tasks.forms import TaskForm
from tasks.models import Task
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from datetime import date
from django.urls import reverse


# Create your views here.
@login_required
def create_task(request):
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(False)
            task.assignee = request.user
            task.save()
            return redirect("show_project", id=task.project.id)
    else:
        form = TaskForm()
        form.fields["assignee"].queryset = User.objects.filter(
            username=request.user
        )

    context = {"form": form}
    return render(request, "tasks/create_task.html", context)


@login_required
def list_task(request):
    lists = Task.objects.filter(assignee=request.user)
    context = {
        "lists": lists,
    }
    return render(request, "tasks/tasks.html", context)


@login_required
def update_task(request, id):
    task = Task.objects.get(id=id)
    if request.method == "POST":
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            task = form.save(commit=False)
            task.is_completed = request.POST.get("is_completed") == "on"
            task = form.save()
            return redirect(reverse("show_project", args=[task.project.id]))
    else:
        form = TaskForm(instance=task)
    context = {"task": task, "form": form, "id": id}
    return render(request, "tasks/edit_task.html", context)


@login_required
def task_detail(request, id):
    detailed = get_object_or_404(Task, id=id)
    context = {"detailed": detailed}
    return render(request, "tasks/detailed.html", context)

tasks/templates/tasks/create_task.html
{% extends "base.html" %}

{% block main %}
<div class="container">
    <h1> Create a new task </h1>
    {% if form.error %}
    <p>{{ message }}</p>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button class="button inverse-button w-button">Create</button>
    </form>
</div>
{% endblock %}

tasks/templates/tasks/detailed.html
{% extends "base.html" %}

{% block main %}
<div class="section-padding">
    <div class="container">
        <p><a class="link-light" href="{% url 'mytasks:show_my_tasks' %}">Return to list</a></p>
        <div class="container-task">
            <h1 class="heading-1">{{ detailed.name }}</h1>
            <h2>Due: {{ detailed.due_date }}</h2>
            <p class="subheader">Assigned To: {{ detailed.assignee }}</p>
            <p class="subheader">Description: {{ detailed.description }}</p>
            <p><a class="link-light" href="{% url 'mytasks:edit_tasks' detailed.id %}">Edit Task</a></p>
        </div>
    </div>
</div>
{% endblock %}

tasks/templates/tasks/edit_task.html
{% extends "base.html" %}

{% block main %}
<div class="container">
    <h1> Edit {{ task.name }} </h1>
    {% if form.error %}
    <p>{{ message }}</p>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button class="button inverse-button w-button">Edit</button>
    </form>
</div>
{% endblock %}

tasks/templates/tasks/tasks.html
{% extends "base.html" %}
{% load tz %}

{% block main %}
<div class="container">
    <h1>My Tasks</h1>
    {% if lists %}
    <table>
        <thead>
            <th>Name</th>
            <th>Start date</th>
            <th>Due date</th>
            <th>Is completed</th>
            <th>Edit</th>
        </thead>
        <tbody>
            {% for task in lists %}
            <tr>
                <td class="tasks">{{ task.name }} </td>
                <td>{{ task.start_date }}</td>
                {% if task.due_date < now %} <td class="danger">
                    {% else %}
                    <td>
                        {% endif %}{{ task.due_date }}</td>
                    <td>{{ task.is_completed|yesno }}</td>
                    <td><a class="link-light" href="{% url 'mytasks:edit_tasks' task.id %}"> Edit </a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>You have no tasks</p>
    {% endif %}
    {% endblock %}