home/urls.py
from django.urls import path, include
from home.views import home_page, about_page

urlpatterns = [
    path("home/", home_page, name="home_page"),
    path("about/", about_page, name="about_page"),
]

projects/urls.py
from django.urls import path
from projects.views import (
    list_projects,
    project_detail,
    create_project,
    start_project_detail,
    team_list,
    create_category,
    task_by_tag,
)

urlpatterns = [
    path("demo/", start_project_detail, name="demo"),
    path("list/", list_projects, name="list_projects"),
    path("<int:id>/", project_detail, name="show_project"),
    path("create/", create_project, name="create_project"),
    path("create/category/", create_category, name="create_category"),
    path("team/", team_list, name="list_team"),
    path("tag/", task_by_tag, name="task_by_tag"),
]

tasks/urls.py
from django.urls import path
from tasks.views import (
    create_task,
    list_task,
    update_task,
    task_detail,
)

app_name = "mytasks"

urlpatterns = [
    path("create/", create_task, name="create_task"),
    path("mine/", list_task, name="show_my_tasks"),
    path("mine/<int:id>/edit/", update_task, name="edit_tasks"),
    path("mine/<int:id>/detail/", task_detail, name="task_detail"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect


def redirect_to_home(request):
    return redirect("home_page")


def redirect_to_login(request):
    return redirect("login")


def redirect_to_project(request):
    return redirect("list_projects")


urlpatterns = [
    path("", redirect_to_home, name="home"),
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path("accounts/", include("accounts.urls")),
    path("accounts/", redirect_to_login, name="account_page"),
    path("projects/", redirect_to_project, name="project_page"),
    path("tasks/", include("tasks.urls", namespace="mytasks")),
    path("", include("home.urls")),
]

projects/models.py
from django.db import models
from django.conf import settings

# Create your models here.
USER_MODEL = settings.AUTH_USER_MODEL


class ProjectCategory(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Team(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    members = models.ManyToManyField(
        USER_MODEL,
        related_name="teams",
    )

    def __str__(self):
        return self.name


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="projects",
        on_delete=models.CASCADE,
        null=True,
    )
    team = models.ForeignKey(
        Team,
        related_name="projects",
        on_delete=models.CASCADE,
        null=True,
    )
    category = models.ManyToManyField(
        ProjectCategory,
        related_name="projects",
    )

    def __str__(self):
        return self.name


class ProjectUpdate(models.Model):
    class ProjectStatus(models.TextChoices):
        Green = "Green"
        Amber = "Amber"
        Red = "Red"

    project = models.ForeignKey(
        Project,
        related_name="updates",
        on_delete=models.CASCADE,
        null=True,
    )
    scope = models.CharField(
        max_length=50,
        null=True,
        choices=ProjectStatus.choices,
        default=ProjectStatus.Green,
    )
    schedule = models.CharField(
        max_length=50,
        null=True,
        choices=ProjectStatus.choices,
        default=ProjectStatus.Green,
    )
    cost = models.CharField(
        max_length=50,
        null=True,
        choices=ProjectStatus.choices,
        default=ProjectStatus.Green,
    )
    update = models.TextField(null=True)

projects/forms.py
from django.forms import ModelForm
from projects.models import (
    Project,
    Team,
    ProjectCategory,
    ProjectUpdate,
    USER_MODEL,
)


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = [
            "name",
            "description",
            "owner",
            "team",
            "category",
        ]


class ProjectCategoryForm(ModelForm):
    class Meta:
        model = ProjectCategory
        fields = [
            "name",
        ]


class ProjectUpdatesForm(ModelForm):
    class Meta:
        model = ProjectUpdate
        fields = [
            "project",
            "scope",
            "schedule",
            "cost",
            "update",
        ]

projects/views.py
from django.shortcuts import render, get_object_or_404, redirect
from projects.models import (
    Project,
    ProjectCategory,
    ProjectUpdate,
    Team,
    USER_MODEL,
)
from django.contrib.auth.decorators import login_required
from projects.forms import (
    ProjectForm,
    ProjectCategoryForm,
    ProjectUpdatesForm,
)
from tasks.models import Task, TaskTag
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your views here.
def start_project_detail(request):
    detail = get_object_or_404(Project, id=1)
    context = {"detail": detail}
    return render(request, "projects/detail.html", context)


@login_required
def list_projects(request):
    lists = Project.objects.filter(owner=request.user)
    tasks = Task.objects.filter(assignee=request.user)
    context = {
        "lists": lists,
        "tasks": tasks,
    }
    return render(request, "projects/list.html", context)


@login_required
def project_detail(request, id):
    detail = get_object_or_404(Project, id=id)
    categories = detail.category.all()
    category_tasks = {}
    for category in categories:
        category_tasks[category] = detail.tasks.filter(category=category)
    context = {
        "detail": detail,
        "categories": categories,
        "category_tasks": category_tasks,
    }

    context = {"detail": detail, "categories": categories}
    return render(request, "projects/detail.html", context)


@login_required
def create_project(request):
    if request.method == "POST":
        form = ProjectForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("list_projects")
    else:
        form = ProjectForm()

    context = {"form": form}
    return render(request, "projects/create.html", context)


@login_required
def create_category(request):
    if request.method == "POST":
        form = ProjectCategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("list_projects")
    else:
        form = ProjectCategoryForm()

    context = {"form": form}
    return render(request, "projects/create_category.html", context)


@login_required
def team_list(request):
    teams = Team.objects.filter(members=request.user)
    context = {"teams": teams}
    return render(request, "projects/teams/team_list.html", context)


@login_required
def task_by_tag(request):
    user = request.user
    projects = Project.objects.filter(owner=user)
    tags = TaskTag.objects.all()

    task_data = {}
    for tag in tags:
        task_data[tag.tag] = {}
        for project in projects:
            tasks = Task.objects.filter(
                assignee=user, project=project, tag=tag
            )
            task_data[tag.tag][project.name] = tasks

    context = {"task_data": task_data}
    return render(request, "projects/task_by_tag.html", context)


@receiver(post_save, sender=Task)
def update_project_category(sender, instance, **kwargs):
    """
    Update the related project's categories based on the assigned task category
    """
    if instance.project:
        project = instance.project
        if instance.category not in project.category.all():
            project.category.add(instance.category)

projects/templates/projects/create.html
{% extends "base.html" %}

{% block main %}
<div class="section-padding">
    <div class="container">
        <h1> Create a new project </h1>
        {% if form.error %}
        <p>{{ message }}</p>
        {% endif %}
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button class="button inverse-button w-button">Create</button>
        </form>
    </div>
</div>
{% endblock %}

projects/templates/projects/create_category.html
{% extends "base.html" %}

{% block main %}
<div class="container">
    <h1> Create a new project category </h1>
    {% if form.error %}
    <p>{{ message }}</p>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button class="button inverse-button w-button">Create</button>
    </form>
</div>
{% endblock %}

projects/templates/projects/detail.html
{% extends "base.html" %}
{% load static %}

{% block main %}
<div class="section-padding">

    <div class="container">
        <div class="container-center">
            <div class="text-center">
                <div class="text-cemter-top">
                    <div class="accordion-header">
                        <h2 class="heading-2 purple-text">{{ detail.name }}</h2>
                    </div>
                </div>
                <div class="light-purple-text">
                    <p class="p-center">{{ detail.description }}</p>
                </div>
            </div>
        </div>
        <h2>Tasks</h2>
        <p><a class="link-light" href="{% url 'mytasks:create_task' %}">Create a new task</a></p>
        <div class="accordion-wrapper">
            <div id="my-accordion" class="accordion-card">
                <div class="accordion-grid w-layout-grid">
                    <div class="accordion-item-wrapper">
                        <div class="accordion-sub-wrap">
                            <div class="accordian-header">
                                <div class="accordian-header">
                                    <h3 class="accordion-title">Test</h3>
                                </div>
                            </div>
                            <div id="myContent"
                                style="height:0px;-webkit-transform:translate3d(null, 20px, 0) scale3d(0.96, 0.96, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-moz-transform:translate3d(null, 20px, 0) scale3d(0.96, 0.96, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-ms-transform:translate3d(null, 20px, 0) scale3d(0.96, 0.96, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);transform:translate3d(null, 20px, 0) scale3d(0.96, 0.96, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);opacity:0"
                                class="accordion-body-wrapper">
                                <div class="accordion-space"></div>
                                <div class="light-purple-text">
                                    <p>Things about Item</p>
                                </div>
                            </div>
                        </div>
                        <div class="accordion-right">
                            <a href="myContent" class=" accordion-buttton w-inline-block"
                                src="{% static '/images/arrow.svg' %}"
                                alt="Icon - Elements Webflow Library - BRIX Templates" class="accordion-arrow"></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div>
            <h2>Categories</h2>
        </div>
        {% for category in categories %}
        {% if category.tasks.all %}
        <p class="subheader">{{ category.name }}</p>
        {% if detail.tasks.exists %}

        <table class="fixed-table">
            <thead>
                <th>Name</th>
                <th>Assignee</th>
                <th>Start date</th>
                <th>Due date</th>
                <th>Is completed</th>
                <th>Edit</th>
            </thead>
            <tbody>
                {% for task in category.tasks.all %}
                <tr>
                    <td class="tasks">{{ task.name }}</td>
                    <td>{{ task.assignee }}</td>
                    <td>{{ task.start_date|date:"m/d/Y" }}</td>
                    <td>{{ task.due_date|date:"m/d/Y" }}</td>
                    <td><input type="checkbox" name="is_completed" {% if task.is_completed %} checked{% endif %}>
                    </td>
                    <td>
                        {% if user.is_authenticated and user == task.assignee %}
                        <a class="link-light" href="{% url 'mytasks:edit_tasks' task.project.id %}"> | Edit</a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p>This project has no tasks</p>
        {% endif %}
        {% endif %}
        {% endfor %}
    </div>
</div>
</div>
</div>


{% endblock %}

projects/templates/projects/list.html
{% extends "base.html" %}

{% block main %}
<div class="section-padding">
    <div class="container">
        <h1>My Projects</h1>
        <p><a class="link-light" href="{% url 'create_project' %}">Create a new project</a></p>

        {% if lists %}
        <table>
            <thead>
                <th>Name</th>
                <th>Number of Tasks</th>
            </thead>
            <tbody>
                {% for project in lists %}
                <tr>
                    <td><a class="link-light" href="{% url 'show_project' id=project.id %}">{{ project.name }}</a></td>
                    <td>{{ project.tasks.all|length }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <p><a class="link-light" href="{% url 'create_category' %}">Create a project category</a></p>
        <p>Assign tags</p>

        {% else %}
        <p>You are not assigned to any projects.</p>
        {% endif %}
    </div>
</div>
{% endblock %}

projects/templates/projects/task_by_tag.html
{% extends "base.html" %}

{% block main %}
<h1>My Tasks by Tag</h1>
{% if task_data %}
{% for tag, projects in task_data.items %}
<h2>{{ tag }}</h2>
{% if projects %}
{% for project, tasks in projects.items %}
<h3>{{ project }}</h3>
<ul>
    {% for task in tasks %}
    <li>{{ task.name }}</li>
    {% endfor %}
</ul>
{% endfor %}
{% else %}
<p>No tasks found.</p>
{% endif %}
{% endfor %}
{% else %}
<p>No task data available.</p>
{% endif %}
{% endblock %}